# Generated by Django 4.2.4 on 2023-08-22 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlayerModels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GameModels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameColModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_1', models.IntegerField()),
                ('field_2', models.IntegerField()),
                ('field_3', models.IntegerField()),
                ('field_4', models.IntegerField()),
                ('field_5', models.IntegerField()),
                ('field_6', models.IntegerField()),
                ('three_of_kind', models.IntegerField()),
                ('four_of_kind', models.IntegerField()),
                ('full_house', models.IntegerField()),
                ('small_flush', models.IntegerField()),
                ('big_flush', models.IntegerField()),
                ('general', models.IntegerField()),
                ('chance', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GameColModels', to=settings.AUTH_USER_MODEL)),
                ('player_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GameColModels', to='dices.playermodel')),
            ],
        ),
    ]
