# Generated by Django 4.2.4 on 2023-08-31 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dices', '0002_alter_playermodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecolmodel',
            name='game_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='GameColModels', to='dices.gamemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='game_name',
            field=models.CharField(default='Game 2023-08-31 19:09', max_length=100),
        ),
    ]
