# Generated by Django 4.2.4 on 2023-09-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dices', '0005_alter_gamecolmodel_big_flush_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='game_name',
            field=models.CharField(default='Game 2023-09-02 08:41', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='gamecolmodel',
            unique_together={('id', 'player_fk')},
        ),
    ]
