# Generated by Django 4.2.4 on 2023-09-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dices', '0006_alter_gamemodel_game_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='game_name',
            field=models.CharField(default='Game 2023-09-02 08:42', max_length=100),
        ),
    ]
