# Generated by Django 4.2.4 on 2023-09-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dices', '0007_alter_gamemodel_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='game_name',
            field=models.CharField(default='Game 2023-09-02 08:43', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='gamecolmodel',
            unique_together={('game_fk', 'player_fk')},
        ),
    ]
